EstokMaster/EstokMaster/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstokMaster.Controllers
{
    public class CadastroController : Controller
    {
        // GET: Cadastro
        public ActionResult GrupoProduto()
        {
            return View();
        }
        public ActionResult MarcaProduto()
        {
            return View();
        }
        public ActionResult LocalProduto()
        {
            return View();
        }
        public ActionResult UnidadeMedida()
        {
            return View();
        }
        public ActionResult Produto()
        {
            return View();
        }
        public ActionResult Pais()
        {
            return View();
        }
        public ActionResult Estado()
        {
            return View();
        }
        public ActionResult Cidade()
        {
            return View();
        }
        public ActionResult Fornecedor()
        {
            return View();
        }
        public ActionResult PerfilUsuario()
        {
            return View();
        }
        public ActionResult Usuario()
        {
            return View();
        }
        

    }
}

EstokMaster/EstokMaster/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EstokMaster.Controllers
{
    public class OperacaoController : Controller
    {
        // GET: Operacao
        public ActionResult EntradaEstoque()
        {
            return View();
        }
        public ActionResult SaidaEstoque()
        {
            return View();
        }
        public ActionResult LancPerdaProduto()
        {
            return View();

        }
        public ActionResult Inventario()
        {
            return View();
        }
    }
}

EstokMaster/EstokMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="mais opções">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("StokMaster", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Grupo de Produtos", "GrupoProduto", "Cadastro")</li>
                        <li>@Html.ActionLink("Marcas de Produtos", "MarcaProduto", "Cadastro")</li>
                        <li>@Html.ActionLink("Locais de Armazenamento", "LocalProduto", "Cadastro")</li>
                        <li>@Html.ActionLink("Unidades de medida", "UnidadeMedida", "Cadastro")</li>
                        <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                        <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                        <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                        <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                        <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                        <li>@Html.ActionLink("Perfis de Usuários", "PerfilUsuario", "Cadastro")</li>
                        <li>@Html.ActionLink("Usuários", "Usuario", "Cadastro")</li 
                     </li>
                    <li>
                </ul>
                    <li>
                    
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operações<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Entrada de Produtos", "EntradaEstoque", "Operacao")</li>
                            <li>@Html.ActionLink("Saida de Produtos", "SaidaEstoque", "Operacao")</li>
                            <li>@Html.ActionLink("Lnaçamntos de Perdas", "LancPerdaProduto", "Operacao")</li>
                            <li>@Html.ActionLink("Intentário de Estoque", "Inventario", "Operacao")</li>
                        </ul>
                
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Reposição do Estoque", "PosicaoEstoque", "Relatorio")</li>
                            <li>@Html.ActionLink("Ressuprimento ", "Ressuprimento", "Relatorio")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Graficos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Perdas do Mes", "PerdaMesa", "Grafico")</li>
                            <li>@Html.ActionLink("Entradas vs Saidas do Mês ", "EntradaSaidaMes", "Grafico")</li>
                        </ul>
                    </li>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - StockMaster ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>